on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Sync to personal repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.AUTO_ACTIONS }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "${{ secrets.EMAIL }}"
          
          # Add personal repository as a remote
          git remote add personal https://rlawnsrud0509:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/rlawnsrud0509/BSM.GG-Frontend_v2.git
          
          # Push to personal repository
          git push personal main --force

